---
title: "Victor Cameron"
author: "Victor Cameron"
date: "`r Sys.Date()`"
output: 
   pagedown::html_resume:
    css: ['css/styles.css', 'resume', 'https://cdn.rawgit.com/jpswalsh/academicons/master/css/academicons.min.css']
    self_contained: true
---

Aside
====================================

Coordonnées
------------------------------------

<i class="fa fa-envelope"></i> victor.cameron@usherbrooke.ca<br>
<!-- <i class="fa fa-twitter"></i> [CameronVictor5](https://twitter.com/CameronVictor5)<br> -->
<i class="fa fa-github"></i> [vcameron1](https://github.com/vcameron1)<br>
<i class="ai ai-google-scholar"></i> [Publications](https://scholar.google.com/citations?user=5syOaukAAAAJ&hl=fr)<br>
<i class="ai ai-orcid"></i> [0000-0003-0624-4201](https://orcid.org/0000-0003-0624-4201)<br>


Expertise
------------------------------------
<span style="font-weight:600;">Écologie</span> <br>
<span style="font-weight:600;">Programmation</span>: <br>R, C++<br>
<span style="font-weight:600;">Analyse et représentation de données</span>: <br>R, C++<br>
<span style="font-weight:600;">Base de données</span>: <br>SQLite <br>(Connaissances de base)<br>
<span style="font-weight:600;">Rédaction et présentation</span>: <br>Suite Ms Office, Google Slides, Markdown, LaTeX<br>


Langues
------------------------------------

**Français**<span style="font-size:11px;"> Natif</span><br>
**Anglais**<span style="font-size:11px;"> Professionnel</span><br>


Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Fait avec [**pagedown**](https://github.com/rstudio/pagedown).

Le code source est disponible à [github.com/vcameron1/resume](https://github.com/vcameron1/resume).

Dernière mise à jour `r Sys.Date()`.

[<i class='fas fa-download'></i> Télécharger la version PDF](https://vcameron1.github.io/resume/VictorCameron.pdf)



Main
================================================================================

 <span style="font-weight:600">Victor Cameron</span> <span style="font-size: 13px;"> <!--MSc.--></span>{#title}
--------------------------------------------------------------------------------


<span style="font-size: 1rem;">< <i class="fa fa-chart-bar"></i> + <i class="fa fa-laptop"></i> > Écologiste, communicateur et scientifique des données </span>

<span style="font-size: 1rem;">< <i class="fa fa-tree"></i> + <i class="fa fa-bicycle"></i> > Athlète accompli et passionné de la nature

<br>

### Profil

- Formation en écologie numérique
- Expérience en science des données 
- Développement de formations numériques et d'écologie
- Leadership dans la gestion et le développement de projet
<!--- Ultra marathonien -->

### Compétences clés 

- Compétences en programmation, en statistique et en analyse de données
- Conceptualisation d'analyses et de visualisation sommatives
- Développement de librairies numériques
- Pédagogie de l'enseignement


Éducation {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### Maitrise de type recherche | Écologie numérique

[Laboratoire d'écologie intégrative](http://ielab.recherche.usherbrooke.ca) - Université de Sherbrooke

Sherbrooke, CA

2019 - 2022

- Étude des effets des changements climatiques sur les dynamiques de la distribution de la biodiversité

### Microprogramme de 2e cycle de formation initiale en enseignement au collégial (MIFIEC)

[Faculté d'enseignement](https://www.usherbrooke.ca/education/) - Université de Sherbrooke

Sherbrooke, CA

2021 - 2022

- Élaboration et présentation d’activités d’apprentissage qui tiennent compte des pratiques pédagogiques appropriées

### Microprogramme de 2e cycle en interactions scientifiques
  
[Faculté des sciences](https://www.usherbrooke.ca/sciences/) - Université de Sherbrooke
  
Sherbrooke, CA
  
2019 - 2021
  
- Animer des discussions, communiquer efficacement des concepts scientifiques et développer ses réflexions sur des problématiques du domaine de la biologie 

### Baccalauréat en biologie | Diplôme Honours

Université McGill (3.60/4.00)

Montréal, CA

2015 - 2019

- Projets de recherche en écologie : dynamiques de la portée des distributions (Hargreaves Lab) et impacts écosystémiques d’une espèce invasive (Ricciardi Lab)
- Concentration mineure en histoire naturelle

### DEC | Sciences de la nature, sport étude

Collège Montmorency (31.6)

Laval, CA

2012 - 2015

- Cours suivis en parallèle à un parcours compétitif de niveau national. 


Expériences Professionnelles {data-icon=suitcase data-concise=true}
--------------------------------------------------------------------------------

### Entraineur de patinage de vitesse 

[Club de patinage de vitesse de Sherbrooke](https://www.cpvs.org)

Sherbrooke, CA

2011 - Aujourd'hui

- Auparavant à [Club de patinage de vitesse de Laval](https://www.patinlaval.ca/crcp/) (2011 - 2019)
- Réalisation de sessions d’entrainement visant à perfectionner des habiletés techniques, tactiques, physiques et à offrir un environnement optimal pour le développement d’athlètes
- Planification de sessions répondant à des objectifs précis

### Atelier sur le parcours en science postsecondaire

École secondaire La Montée

Sherbrooke, Ca

2021

- Développement et animation d'un atelier sur la pratique de la science et sur les études postsecondaires en science 
  - Présentation du parcours et des travaux de recherche
  - Rencontres orientantes avec les étudiants en sciences de l'école secondaire La Montée afin de leur faire découvrir les sciences

### Co-rédaction d'un livre d'accompagnement aux ateliers du centre des sciences de la biodiversité du Québec

CSBQ

Montréal, CA

2021

- Développement du matériel écrit servant à la formation

<!--
### Présentation d'ateliers d'introduction aux outils en science de la biodiversité

CSBQ

Montréal, CA

2020 - 2021

- Développement et présentation d'ateliers d'introduction aux étudiants gradués et au corps facultaire des universités du Québec visant à développer les compétences numériques nécessaires aux sciences de la biodiversité
-->
### Atelier sur les modèles linéaires généralisés

CSBQ

Montréal, CA

2021

- Atelier sur les fondements et l'utilisation d'une méthode d'analyse statistique
- Atelier développé pour et présenté aux étudiants gradués et au corps facultaire des universités du Québec
  
### Charger et manipuler des données
  
CSBQ
  
Montréal, CA
  
2020
  
- Atelier sur les fondements et l'utilisation de données pour en faire l'analyse
- Atelier développé pour et présenté aux étudiants gradués et au corps facultaire des universités du Québec
  
### Introduction à R
  
CSBQ
  
Montréal, CA
  
2020
  
- Atelier d'introduction au langage de programmation R
- Atelier développé pour et présenté aux étudiants gradués et au corps facultaire des universités du Québec


### Entraineur-chef

[Club de patinage de vitesse de Laval Ste-Dorothée](https://www.patinlaval.ca/ste-dorothee/)

Laval, CA

2013 - 2016

- Gestion d'une école de patin de 125 jeunes de 4 à 15 ans et d'une équipe d'entraineurs, d'assistants et d'aides

<!--
### Aide Technicien en climatisation/chauffage

[Thermo-teck](https://www.pagesjaunes.ca/bus/Quebec/Saint-Laurent/Thermo-Teck/101954778.html)

Montréal, CA

2016 - 2018

- Installation et réparation de systèmes de climatisation/chauffage
- Travail manuel et résolution de problèmes
-->

Bourses et prix {data-icon=star}
--------------------------------------------------------------------------------

### Bourse de recherche (11667$)

[BIOS2](http://bios2.usherbrooke.ca/fr/accueil-2/)

Sherbrooke, CA

2020

- Bourse obtenue suite à un concours où un comité évalue les candidatures et les propositions de projet dans un processus anonyme

### Mention du doyen pour la recherche multidisciplinaire au premier cycle

Université McGill

Montréal, CA

2019

- La mention est accordée aux étudiants ayant complété différents projets de recherche indépendants dans au moins deux départements distincts de l’université
  
### Bourse régionale sport-étude de la Fondation Desjardins (500$)

[Alliance sport-étude](https://alliancesportetudes.ca)

Laval, CA

2015

- La bourse régionale de la fondation sport-étude récompense l’étudiant-athlète pour son succès au niveau des résultats académiques et sportifs


### Vice - champion canadien au 500m et au relais

Patinage de vitesse

Canada

2013


Publications (Peer-reviewed journals) {data-icon=book}
--------------------------------------------------------------------------------

### Spatial distribution and conservation hotspots of mammals in Canada

FACETS <a href="{https://doi.org/10.1139/facets-2020-0018}" target="_blank"><i class="ai ai-doi"></i></a>

N/A

2020

<span style="text-decoration: underline;">Cameron, V.</span>, & Hargreaves, A. L.

### Spatial structure is more than habitat amount: a metapopulation approach is necessary to capture distribution changes under climate change

En préparation

N/A

2022

<span style="text-decoration: underline;">Cameron, V.</span>, Blanchet, G., Boulanger, Y., Tremblay, J., & Gravel, D.


Formation scientifique {data-icon=flask data-concise=true}
--------------------------------------------------------------------------------

### Stage à Ressources Naturelles Canada

Ressources Naturelles Canada

N/A

2021

- Modélisation des changements de distribution en réponse aux changements climatiques d'une espèce menacée (Grive de Bicknell)

### École d'été en modélisation de la biodiversité | Modèles Bayesiens

Université de Sherbrooke & BIOS2

N/A

2021

- Méthodes pour ajuster les modèles aux données écologiques

### BIOS2-G3E working group

BIOS2 & G3E

N/A

2021

- Analyse primaire de l’impact des changements climatiques sur la biodiversité des petits cours d’eau du Québec

### CIEE - BIOS2 synthesis working group

CIEE & BIOS2

N/A

2020

- Synthétiser 50 ans de changements d'abondance et de composition chez les poissons et mollusques du golfe du St-Laurent


### Stage à Conservation de la Nature Canada

[Conservation de la Nature Canada](https://www.natureconservancy.ca/fr/)

Montréal, CA

2020

- Conception d'un outil de science citoyenne pour la collection de données sur le terrain

### Projet de recherche Honours

[Hargreaves Lab](https://annahargreaves.wixsite.com/home)

Montréal, CA

2018 - 2019

- Écologie | Étude de l'effet de la distribution des mammifères 'canadiens' sur leur statut de conservation et sur les régions à prioriser pour la conservation de ces espèces
- Analyse de données et statistiques sur R | Data science | Données spatiales de COSEWIC et de IUCN

### Projet de recherche indépendant

[Ricciardi Lab](http://redpath-staff.mcgill.ca/ricciardi/)

Montréal, CA

2018

- Écologie | Étude de l'effet de l'habitat sur l'impact qu'une espèce invasive (Gobie) a sur les communautés du Saint-Laurent
- Expériences en laboratoire et analyse de données sur R | Réponses fonctionnelles | Interaction prédateur-proie


Conférences et affiches {data-icon=chalkboard}
--------------------------------------------------------------------------------

### Spatial distribution and conservation of terrestrial mammals in Canada

Colloque annuel du QCBS

Montréal, CA

2019

- ([poster](https://github.com/vcameron1/resume/docs/CSBQ2019.pdf))


Certifications {data-icon=certificate}
--------------------------------------------------------------------------------

### Permis de possession et acquisition d'une arme à feu

Gouvernement du Canada

N/A

2021

### Patinage de vitesse compétition - Développement (anciennement niv. 3)

PVC

N/A

2019

### Permis de conduire de classe 5

Gouvernement du Québec

N/A

2011
